paths:
  data_path: data/Icons-50.pkl
  classes_path: data/classes.txt
  save_path: models/
  filt_save_path: models/filt/
params:
  latent_dim: 100
  num_classes: 50
  image_size: 32
  channels: 3
  epochs: 100
  batch_size: 50
  shuffle: True
optim:
  lr: 0.0002
  beta_1: 0.5
