paths:
  data_path: Icons-50.pkl
  save_path: models/
  filt_save_path: models/filt/
  gen_path: generator.h5
  disc_path: discriminator.h5
  cgan_path: cgan.h5
params:
  latent_dim: 100
  num_classes: 50
  image_size: 32
  channels: 3
  epochs: 100
  batch_size: 50
  shuffle: True
optim:
  lr: 0.0002
  beta_1: 0.5
